### PR TITLE
Add blog posts to website

### PR DESCRIPTION
**Pull request by soerendomroes**
The idea is that new features (or old ones) get a blog post when they are introduced to showcase how they work.

This PR is work in progress feel free to give feedback about presentation or content, since I am not quite sure what should actually be in a blogpost.

### Potential wants
- [ ] New features and their interaction/limitation?
- [ ] Example/Links to examples using features?
- [ ] Pictures how a layout with these features can look like?
- [ ] Link to corresponding publication?

### Don't wants
- give additional information that is not already documented elsewhere
- explain in detail how the algorithm works

### Questions
- How should the features be presented, is a link sufficient?
- TODO

### CODE REVIEW

**Review by spoenemann — COMMENTED** [review]
The content looks good so far! A few images with example layouts would be helpful, but other than that it covers the important questions I would have as a user about a new feature: what does it improve and how can I configure it?

**Comment by soerendomroes** [comment]
Thanks @spoenemann, I added some images. If you don't have other suggestions, I will merge this and try to add other blogposts  if I find the time.

**Comment by spoenemann** [comment]
Yes thank you! Is there a way to preview the website from the PR?

**Comment by soerendomroes** [comment]
Yes, checkout the branch and run `hugo && hugo server` inside the docs directory.

**Comment by spoenemann** [comment]
Oh, so I need to install that locally first. It would be great to have a Gitpod configuration so such PRs can be easily verified in a cloud workspace. But that's a different topic, feel free to merge this.

**Pull request merged**
