### PR TITLE
Graph.Json: Improve support for edge containment.

### PR DESCRIPTION
**Pull request by skieffer**
* Ensure all edges have proper containment after building a graph
  from JSON.
* Write a `container` property into each edge after layout. This
  gives the `id` of the node that was this edge's container, and
  helps the user interpret the route points in the right coord
  system.

### CODE REVIEW

**Comment by skieffer** [comment]
Further discussion [here](https://github.com/eclipse/elk/issues/776).

**Comment by uruuru** [comment]
Sorry for the late entry - I've been on vacation. 

### Discussion
I believe part of the issue here is that the elkjs tests are outdated and nobody realized it. As you point out 
>The unit test is failing because the edge is now considered when its container A
is laid out, and now it is satisfying the connectsToGraph condition. So the edge
gets a layout, *which the unit test says it should not.*

The hierarchy-handling code has been revised since the elkjs test has been created and -- this is the problematic part -- changed it's behavior from always failing silently to raising an exception in some cases. 

The edge containment of the elkjs test is in fact invalid, however, briefly skimming the issue, I believe it didn't matter for the test itself as long as the edge is excluded from layout. 


>  Do you really not want these connectsToGraph-type edges to
get a layout when operating in 'hierarchyHandling': 'SEPARATE_CHILDREN' mode?

Yes, the only intended way to model hierarchy-crossing edges in this case is via ports.

> If that is really correct, then I think the right fix is to simply throw away the
connectsToGraph condition in the importFlatGraph() method.

Tbh, there are several cases that one tends to forget or is not aware of at this point. For instance, _inside self loops_ caused several headaches and @le-cds spent quite some time there. Hence, I'd like to change this part as little as possible. 

### Proposal
That being said, I'd suggest
* to revert 71ff75f8845a70ca5defca2709bf7fab1549bd45 and 
* to fix the elkjs tests (I'll take care of that).

Does that make sense?

Regarding your changes to the tests, I'd have a brief look at the issues themselves to check if they "allow" hierarchy handling to be set. 

### Failing unit test
Tbh, I have no idea why crossing minimization should fail. We've seen non-deterministic issues once in a while lately.

**Comment by skieffer** [comment]
Hey Ulf, glad you had a vacation!

Okay, this starts to make a lot more sense. I really did have doubts about whether the `elkjs` `test-bug-8` truly motivated such a drastic change as I had suggested on `ElkGraphImporter`.

I just have one question below (should I also revert my changes on Issues 546 & 680?).


### Issues 546 & 680

I'm thinking that actually in addition to reverting [`71ff75f`](https://github.com/eclipse/elk/commit/71ff75f8845a70ca5defca2709bf7fab1549bd45) I should also just revert my changes on these tests too.

Wanted to check with you first, because I'm still not 100% sure I'm understanding everything.

>> Do you really not want these connectsToGraph-type edges to
>> get a layout when operating in 'hierarchyHandling': 'SEPARATE_CHILDREN' mode?

> Yes, the only intended way to model hierarchy-crossing edges in this case is via ports.

Aha. Well the thing is, the graphs in the 548 & 680 unit tests _do_ use ports. So I guess they are meant to work properly in `SEPARATE_CHILDREN` mode. And in fact they _do_ work just fine in that mode, after I revert [`71ff75f`](https://github.com/eclipse/elk/commit/71ff75f8845a70ca5defca2709bf7fab1549bd45).

So, shall I just revert my changes to these tests too?



### `LayerSweepCrossingMinimizerTest`

I should have been more explicit, that for me the errors seem to be one of those Java "illegal reflective access" things. I suspect it may have only to do with my particular combination of Java version with other components. The error reports looked like this:

```
givenSingleHierarchicalNodeWithCross_RemovesCrossing[BARYCENTER](org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizerTest)  Time elapsed: 0.02 s  <<< ERROR!
java.lang.IllegalStateException: Couldn't clone property 'inLayerSuccessorConstraint'. Make sure it's type is registered with the ElkReflect utility class.
    at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizerTest.setUpAndMinimizeCrossings(LayerSweepCrossingMinimizerTest.java:1681)
    at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizerTest.givenSingleHierarchicalNodeWithCross_RemovesCrossing(LayerSweepCrossingMinimizerTest.java:149)
```

and my setup looks like:

```
$ java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```

Anyway the tests seem to have run successfully on GitHub!

**Comment by uruuru** [comment]
> So, shall I just revert my changes to these tests too?

Since you say the tests use ports, I'd say, yes, please revert them. 

Regarding the issue with the test:
```
java.lang.IllegalStateException: Couldn't clone property 'inLayerSuccessorConstraint'. Make sure it's type is registered with the ElkReflect utility class.
```
This is completely independent of the crossing minimization but rather related to the _setup_ of the test/layout framework. 

Could you try adding the following to the test? 
```
import org.eclipse.elk.alg.test.PlainJavaInitialization;
[...]
    @BeforeClass
    public static void init() {
        PlainJavaInitialization.initializePlainJavaLayout();
    }
```

Some background for future reference: to allow compilation to elkjs we had to bypass Java's reflections for certain parts of the code. Details can be found in the doc of [ElkReflect.java](https://github.com/eclipse/elk/blob/bb10f187728162183d7700383a05dd5234006ad6/plugins/org.eclipse.elk.graph/src/org/eclipse/elk/graph/util/ElkReflect.java).

Before a test runs, certain things have to be registered, e.g.:
https://github.com/eclipse/elk/blob/bb10f187728162183d7700383a05dd5234006ad6/plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/data/LayoutMetaDataService.java#L120-L123

Why the list? The layout option reported to cause issues in your case uses a list:
https://github.com/eclipse/elk/blob/bb10f187728162183d7700383a05dd5234006ad6/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/InternalProperties.java#L202

Quite often the _initialization_ has already been performed by a different test or initialization mechanism (this probably happens in the github action). There were times during which the manual registration wasn't required, which is why several tests likely still miss this init part.

**Comment by skieffer** [comment]
> Since you say the tests use ports, I'd say, yes, please revert them.

Okay, done. I realize now that something I wrote in an earlier post misled you: I wrote that in these tests "a child node was connected to its parent node"...because in my mind this was "true"! Now I begin to understand that in fact connecting _through ports_ really makes an important structural difference!

----

Ahhh, okay, the Java reflection stuff is making more sense now -- thanks for the background. I have added the snippet and the test now passes in my setup. I've put it into a separate PR #779 because it's an unrelated issue.

**Pull request merged**
