### PR TITLE
Fixes #405 (invalid port label positions)

### LINKED ISSUE #405: Small port label position offsets between UP and DOWN layout
There are small port label position offsets between the results generated for `DOWN` and `UP` layouts:

screenshot 2019-02-20 at 14 12 05

Note how, in the picture, `P1` and `P2` have slightly different y coordinates.

### PR DESCRIPTION
**Pull request by uruuru**
For details see #405.

### CODE REVIEW

**Comment by uruuru** [comment]
For the record, the following models are checked using the unit tests (and are the result of this fix). 

image

image

image

image

image

**Comment by le-cds** [comment]
Just to be sure that I didn't forget anything: this is ready to merge, right?

**Comment by uruuru** [comment]
If you agree with the change and the tests, yes :).

**Comment by le-cds** [comment]
Agreed and merged!

**Pull request merged**
