### PR TITLE
Fix typo in documentation

### PR DESCRIPTION
**Pull request by olmar**

### CODE REVIEW

**Review by soerendomroes — APPROVED** [review]

**Comment by soerendomroes** [comment]
Thank you for the correction. You need to accept the eclipse eca otherwise I cannot merge this.

**Comment by olmar** [comment]
> Thank you for the correction. You need to accept the eclipse eca otherwise I cannot merge this.

@soerendomroes thanks, I will accept the eclipse eca. Will let you know once done.

**Comment by olmar** [comment]
Added `Signed-off-by` to commit record.

**Comment by soerendomroes** [comment]
> Signed eca. Added `Signed-off-by` to commit record and force pushed.

Very good, I think Signed-off-by is optional nowadays but still nice.

**Pull request merged**
