### PR TITLE
Implemented a textual format for ElkGraph

### LINKED ISSUE #101: Implement a textual format for ElkGraph

### PR DESCRIPTION
**Pull request by spoenemann**
Fixes #101.

In contrast to the older kgt format, the new elkt does not need the `persistentEntries` field for storing properties, but parses directly into the `properties` of EMapPropertyHolder (see #75).

Here's an example graph:
```
algorithm = org.eclipse.elk.layered
edgeRouting = ORTHOGONAL

node n1 {
    layout [ width = 50 height = 50 ]
    nodeLabelPlacement = "OUTSIDE H_CENTER V_BOTTOM"
    portLabelPlacement = OUTSIDE
    portConstraints = FREE
    label "n1"
    
    port p1 {
        layout [ width = 5 height = 5 ]
        label "p1"
    }
    
}
edge n1.p1 -> n2.p1

node n2 {
    layout [ width = 50 height = 50 ]
    nodeLabelPlacement = "OUTSIDE H_CENTER V_BOTTOM"
    portLabelPlacement = INSIDE
    portConstraints = FREE
    label "n2"
    
    port p1 {
        layout [ width = 5 height = 5 ]
        label "Ein erstes langes Port-Label"
    }
    
    port p2 {
        layout [ width = 5 height = 5 ]
        label "Ein zweites langes Port-Label"
    }
    
    node n2_1 {
        layout [
            position = 12.807, 197
            width = 50
            height = 50
        ]
        nodeLabelPlacement = "OUTSIDE H_CENTER V_BOTTOM"
        portLabelPlacement = INSIDE
        portConstraints = FREE
        label "n2_1"
        
        port p1 {
            layout [ width = 5 height = 5 ]
            label "p1"
        }
        
        port p2 {
            layout [ width = 5 height = 5 ]
            label "p2"
        }
        
    }
    edge n2_1.p2 -> p2
    edge p1 -> n2_1.p1 {
        layout [
            start = 32, 438
            bends = 123, 438 | 123, 320 | 92, 320
            end = 92, 300
        ]
        label "Ich bin ein Kanten-Label"
    }
}

edge n2.p1, n2.p2 -> n3.p1 {
    layout [
        section s1 -> s3 [
            incoming = n2.p1
            start = 234, 345
            end = 367, 456
        ]
        section s2 -> s3 [
            incoming = n2.p2
            start = 34, 354
            end = 367, 456
        ]
        section s3 [
            outgoing = n3.p1
            start = 367, 456
            end = 456, 708
        ]
    ]
}

node n3 {
    layout [ width = 50 height = 50 ]
    nodeLabelPlacement = "OUTSIDE H_CENTER V_BOTTOM"
    portLabelPlacement = INSIDE
    portConstraints = FREE
    label "n3"
    
    port p1 {
        layout [ width = 5 height = 5 ]
        label "p1"
    }
}
```

### CODE REVIEW

**Comment by uruuru** [comment]
First of all: thanks! :) 

A couple of comments from my side:
- why is the `layout` defined in an explicit block while the layout options are not? 
- why suddenly square bracket for the layout
- what about using `size` instead of `width` and `height`, similar to `position`?
- are we fine with edges being specified anywhere or should we have a convention?
- personally I like `:` more than `=` but I guess that's just taste

I think I would vote for dropping the layout block and having a `size` field. Although I'm not sure if there's a technical issue with it.

**Comment by le-cds** [comment]
Great work! I'll implement #75 as soon as I get bored on Christmas, which presumably won't take long. ;)

My comments:

* I'm not very happy with the way edge sections work. I don't see a better way, though. What I would do for the textual format would be to try and make the common case as easy as possible: specifying the routing of a simple edge using a single edge section. Perhaps we could change the grammar such that if an edge only has a single edge section, we can simply omit the `section` keyword and put the section's data directly into the `layout` block?

Comments on what Ulf mentioned:

* I was originally going to agree with Ulf to drop the layout block altogether. However, for edges it makes sense to have all the edge sections contained in such a block to set them apart from the rest. Dropping the layout block for everything except for edges introduces inconsistencies, which I would like to avoid. What I would do, though, would be to replace `width` and `height` by `size`.
* Regarding edges being specified all over the place, this cannot be avoided seeing how our graph model is defined. While discussing this, Ulf and I thought that adding a rule to the validator might be the way to go here. That rule would check if the edge's containment node is the one we would expect (as returned by `ElkGraphUtil.findBestEdgeContainment(ElkEdge)`). If the edge containment differs from the one we would expect, the validator could generate a helpful error message. A quick fix might even offer to move the edge definition to the best element automatically.
* Using `:` instead of `=` seemed less intuitive to me at first, but would have an advantage for one of the use cases we often run into: copying property definitions from a graph specified in JSON.

**Comment by spoenemann** [comment]
> why is the layout defined in an explicit block while the layout options are not?

This highlights the difference between `width = 20` and `edgeRouting = ORTHOGONAL`, which might not be obvious otherwise.

> why suddenly square bracket for the layout

I like those more than the previous `layout:` syntax.

> what about using size instead of width and height, similar to position?

Initially I had a single `size` property, but then changed to `width` and `height` so they can be set individually. Or would we always set both together?

> are we fine with edges being specified anywhere or should we have a convention?

A validation rule as proposed by @le-cds is a good idea, but I think it should be a warning and not an error.

> personally I like : more than = but I guess that's just taste

Ok.

> Perhaps we could change the grammar such that if an edge only has a single edge section, we can simply omit the section keyword and put the section's data directly into the layout block?

That's already done, see `edge p1 -> n2_1.p1`

**Comment by le-cds** [comment]
> A validation rule as proposed by @le-cds is a good idea, but I think it should be a warning and not an error.

A warning would be fine with me as well.

> That's already done, see edge `p1 -> n2_1.p1`

Ah, didn't see that one. Good work!

**Comment by uruuru** [comment]
> A warning would be fine with me as well.

I agree. 

> This highlights the difference between width = 20 and edgeRouting = ORTHOGONAL, which might not be obvious otherwise.

I guess together with cds's comment you convinced me :). 

> Initially I had a single size property, but then changed to width and height so they can be set individually. Or would we always set both together?

This would apply to `position` as well, right? I'm for using `size`. I don't think there are too many use cases where you have a default and just want to change one dimension.

**Comment by spoenemann** [comment]
Updated syntax:
```
algorithm: org.eclipse.elk.layered
edgeRouting: ORTHOGONAL

node n1 {
    layout [ size: 50, 50 ]
    nodeLabelPlacement: "OUTSIDE H_CENTER V_BOTTOM"
    portLabelPlacement: OUTSIDE
    portConstraints: FREE
    label "n1"
    
    port p1 {
        layout [ size: 5, 5 ]
        label "p1"
    }
    
}
edge n1.p1 -> n2.p1

node n2 {
    layout [ size: 50, 50 ]
    nodeLabelPlacement: "OUTSIDE H_CENTER V_BOTTOM"
    portLabelPlacement: INSIDE
    portConstraints: FREE
    label "n2"
    
    port p1 {
        layout [ size: 5, 5 ]
        label "Ein erstes langes Port-Label"
    }
    
    port p2 {
        layout [ size: 5, 5 ]
        label "Ein zweites langes Port-Label"
    }
    
    node n2_1 {
        layout [
            position: 12.807, 197
            size: 50, 50
        ]
        nodeLabelPlacement: "OUTSIDE H_CENTER V_BOTTOM"
        portLabelPlacement: INSIDE
        portConstraints: FREE
        label "n2_1"
        
        port p1 {
            layout [ size: 5, 5 ]
            label "p1"
        }
        
        port p2 {
            layout [ size: 5, 5 ]
            label "p2"
        }
        
    }
    edge n2_1.p2 -> p2
    edge p1 -> n2_1.p1 {
        layout [
            start: 32, 438
            bends: 123, 438 | 123, 320 | 92, 320
            end: 92, 300
        ]
        label "Ich bin ein Kanten-Label"
    }
}

edge n2.p1, n2.p2 -> n3.p1 {
    layout [
        section s1 -> s3 [
            incoming: n2.p1
            start: 234, 345
            end: 367, 456
        ]
        section s2 -> s3 [
            incoming: n2.p2
            start: 34, 354
            end: 367, 456
        ]
        section s3 [
            outgoing: n3.p1
            start: 367, 456
            end: 456, 708
        ]
    ]
}

node n3 {
    layout [ size: 50, 50 ]
    nodeLabelPlacement: "OUTSIDE H_CENTER V_BOTTOM"
    portLabelPlacement: INSIDE
    portConstraints: FREE
    label "n3"
    
    port p1 {
        layout [ size: 5, 5 ]
        label "p1"
    }
}
```

**Comment by k644606347** [comment]
> Updated syntax:
> 
> ```
> algorithm: org.eclipse.elk.layered
> edgeRouting: ORTHOGONAL
> 
> node n1 {
>     layout [ size: 50, 50 ]
>     nodeLabelPlacement: "OUTSIDE H_CENTER V_BOTTOM"
>     portLabelPlacement: OUTSIDE
>     portConstraints: FREE
>     label "n1"
>     
>     port p1 {
>         layout [ size: 5, 5 ]
>         label "p1"
>     }
>     
> }
> edge n1.p1 -> n2.p1
> 
> node n2 {
>     layout [ size: 50, 50 ]
>     nodeLabelPlacement: "OUTSIDE H_CENTER V_BOTTOM"
>     portLabelPlacement: INSIDE
>     portConstraints: FREE
>     label "n2"
>     
>     port p1 {
>         layout [ size: 5, 5 ]
>         label "Ein erstes langes Port-Label"
>     }
>     
>     port p2 {
>         layout [ size: 5, 5 ]
>         label "Ein zweites langes Port-Label"
>     }
>     
>     node n2_1 {
>         layout [
>             position: 12.807, 197
>             size: 50, 50
>         ]
>         nodeLabelPlacement: "OUTSIDE H_CENTER V_BOTTOM"
>         portLabelPlacement: INSIDE
>         portConstraints: FREE
>         label "n2_1"
>         
>         port p1 {
>             layout [ size: 5, 5 ]
>             label "p1"
>         }
>         
>         port p2 {
>             layout [ size: 5, 5 ]
>             label "p2"
>         }
>         
>     }
>     edge n2_1.p2 -> p2
>     edge p1 -> n2_1.p1 {
>         layout [
>             start: 32, 438
>             bends: 123, 438 | 123, 320 | 92, 320
>             end: 92, 300
>         ]
>         label "Ich bin ein Kanten-Label"
>     }
> }
> 
> edge n2.p1, n2.p2 -> n3.p1 {
>     layout [
>         section s1 -> s3 [
>             incoming: n2.p1
>             start: 234, 345
>             end: 367, 456
>         ]
>         section s2 -> s3 [
>             incoming: n2.p2
>             start: 34, 354
>             end: 367, 456
>         ]
>         section s3 [
>             outgoing: n3.p1
>             start: 367, 456
>             end: 456, 708
>         ]
>     ]
> }
> 
> node n3 {
>     layout [ size: 50, 50 ]
>     nodeLabelPlacement: "OUTSIDE H_CENTER V_BOTTOM"
>     portLabelPlacement: INSIDE
>     portConstraints: FREE
>     label "n3"
>     
>     port p1 {
>         layout [ size: 5, 5 ]
>         label "p1"
>     }
> }
> ```

> Updated syntax:
> 
> ```
> algorithm: org.eclipse.elk.layered
> edgeRouting: ORTHOGONAL
> 
> node n1 {
>     layout [ size: 50, 50 ]
>     nodeLabelPlacement: "OUTSIDE H_CENTER V_BOTTOM"
>     portLabelPlacement: OUTSIDE
>     portConstraints: FREE
>     label "n1"
>     
>     port p1 {
>         layout [ size: 5, 5 ]
>         label "p1"
>     }
>     
> }
> edge n1.p1 -> n2.p1
> 
> node n2 {
>     layout [ size: 50, 50 ]
>     nodeLabelPlacement: "OUTSIDE H_CENTER V_BOTTOM"
>     portLabelPlacement: INSIDE
>     portConstraints: FREE
>     label "n2"
>     
>     port p1 {
>         layout [ size: 5, 5 ]
>         label "Ein erstes langes Port-Label"
>     }
>     
>     port p2 {
>         layout [ size: 5, 5 ]
>         label "Ein zweites langes Port-Label"
>     }
>     
>     node n2_1 {
>         layout [
>             position: 12.807, 197
>             size: 50, 50
>         ]
>         nodeLabelPlacement: "OUTSIDE H_CENTER V_BOTTOM"
>         portLabelPlacement: INSIDE
>         portConstraints: FREE
>         label "n2_1"
>         
>         port p1 {
>             layout [ size: 5, 5 ]
>             label "p1"
>         }
>         
>         port p2 {
>             layout [ size: 5, 5 ]
>             label "p2"
>         }
>         
>     }
>     edge n2_1.p2 -> p2
>     edge p1 -> n2_1.p1 {
>         layout [
>             start: 32, 438
>             bends: 123, 438 | 123, 320 | 92, 320
>             end: 92, 300
>         ]
>         label "Ich bin ein Kanten-Label"
>     }
> }
> 
> edge n2.p1, n2.p2 -> n3.p1 {
>     layout [
>         section s1 -> s3 [
>             incoming: n2.p1
>             start: 234, 345
>             end: 367, 456
>         ]
>         section s2 -> s3 [
>             incoming: n2.p2
>             start: 34, 354
>             end: 367, 456
>         ]
>         section s3 [
>             outgoing: n3.p1
>             start: 367, 456
>             end: 456, 708
>         ]
>     ]
> }
> 
> node n3 {
>     layout [ size: 50, 50 ]
>     nodeLabelPlacement: "OUTSIDE H_CENTER V_BOTTOM"
>     portLabelPlacement: INSIDE
>     portConstraints: FREE
>     label "n3"
>     
>     port p1 {
>         layout [ size: 5, 5 ]
>         label "p1"
>     }
> }
> ```

Hello, may I ask if there is a detailed documentation;  
I want to know the corresponding JSON syntax

**Comment by k644606347** [comment]
> > Updated syntax:
> > 
> > ```
> > algorithm: org.eclipse.elk.layered
> > edgeRouting: ORTHOGONAL
> > 
> > node n1 {
> >     layout [ size: 50, 50 ]
> >     nodeLabelPlacement: "OUTSIDE H_CENTER V_BOTTOM"
> >     portLabelPlacement: OUTSIDE
> >     portConstraints: FREE
> >     label "n1"
> >     
> >     port p1 {
> >         layout [ size: 5, 5 ]
> >         label "p1"
> >     }
> >     
> > }
> > edge n1.p1 -> n2.p1
> > 
> > node n2 {
> >     layout [ size: 50, 50 ]
> >     nodeLabelPlacement: "OUTSIDE H_CENTER V_BOTTOM"
> >     portLabelPlacement: INSIDE
> >     portConstraints: FREE
> >     label "n2"
> >     
> >     port p1 {
> >         layout [ size: 5, 5 ]
> >         label "Ein erstes langes Port-Label"
> >     }
> >     
> >     port p2 {
> >         layout [ size: 5, 5 ]
> >         label "Ein zweites langes Port-Label"
> >     }
> >     
> >     node n2_1 {
> >         layout [
> >             position: 12.807, 197
> >             size: 50, 50
> >         ]
> >         nodeLabelPlacement: "OUTSIDE H_CENTER V_BOTTOM"
> >         portLabelPlacement: INSIDE
> >         portConstraints: FREE
> >         label "n2_1"
> >         
> >         port p1 {
> >             layout [ size: 5, 5 ]
> >             label "p1"
> >         }
> >         
> >         port p2 {
> >             layout [ size: 5, 5 ]
> >             label "p2"
> >         }
> >         
> >     }
> >     edge n2_1.p2 -> p2
> >     edge p1 -> n2_1.p1 {
> >         layout [
> >             start: 32, 438
> >             bends: 123, 438 | 123, 320 | 92, 320
> >             end: 92, 300
> >         ]
> >         label "Ich bin ein Kanten-Label"
> >     }
> > }
> > 
> > edge n2.p1, n2.p2 -> n3.p1 {
> >     layout [
> >         section s1 -> s3 [
> >             incoming: n2.p1
> >             start: 234, 345
> >             end: 367, 456
> >         ]
> >         section s2 -> s3 [
> >             incoming: n2.p2
> >             start: 34, 354
> >             end: 367, 456
> >         ]
> >         section s3 [
> >             outgoing: n3.p1
> >             start: 367, 456
> >             end: 456, 708
> >         ]
> >     ]
> > }
> > 
> > node n3 {
> >     layout [ size: 50, 50 ]
> >     nodeLabelPlacement: "OUTSIDE H_CENTER V_BOTTOM"
> >     portLabelPlacement: INSIDE
> >     portConstraints: FREE
> >     label "n3"
> >     
> >     port p1 {
> >         layout [ size: 5, 5 ]
> >         label "p1"
> >     }
> > }
> > ```
> 
> Hello, may I ask if there is a detailed documentation; I want to know the corresponding JSON syntax

oo，found it: [https://rtsys.informatik.uni-kiel.de/elklive/conversion.html,](https://rtsys.informatik.uni-kiel.de/elklive/conversion.html,) thanks.

**Comment by soerendomroes** [comment]
@k644606347 If we have the time, we might add a JSON schema for this. The JSON format is also explained in our [documentation](https://eclipse.dev/elk/documentation/tooldevelopers/graphdatastructure/jsonformat.html).

**Comment by peekxc** [comment]
So, this issue is referenced [here](https://eclipse.dev/elk/documentation/tooldevelopers/graphdatastructure/elktextformat.html) as the source spec for the "coming soon", but this PR is listed as merged

**Comment by Eddykasp** [comment]
@peekxc Thanks for pointing that out, I'll open an issue so that someone can get around to it.

**Pull request merged**
