### PR TITLE
[PR] Layered: Comment-related spacings are now inherited. #594

### PR DESCRIPTION
**Pull request by le-cds**
Signed-off-by: Christoph Daniel Schulze <cds@informatik.uni-kiel.de>

### CODE REVIEW

**Comment by uruuru** [comment]
Comments are _only_ placed in the corresponding intermediate processor and then included in the margins of the node, right? The `nodeComment` spacing is also added to the end of the margin?

Wouldn't it hence be required to consider `nodeComment` spacing during the node placement step as well? Example (excuse my paint skills):
image

During node placement `??` will be added. Currently it would be some default, maybe `nodeNode`, right?

**Comment by le-cds** [comment]
> During node placement `??` will be added. Currently it would be some default, maybe `nodeNode`, right?

You're right, the spacings only extend to the end of the comment. Node placement then applies a node-node spacing, even between adjacent comments. I think that's fine, because the node-node spacing is applied between quasi-unrelated nodes.

**Comment by uruuru** [comment]
> You're right, the spacings only extend to the end of the comment.

The top `nodeComment` in my drawing is thus _not_ added at the moment? 

> I think that's fine, because the node-node spacing is applied between quasi-unrelated nodes.

It may be unexpected though. Shall we clearly define it in the options doc: `comment*` spacings are only applied between the comment and the corresponding node. The spacing between comments and anything adjacent is computed as if the comment is a regular node (i.e. `nodeNode`, `nodeEdge`, etc. may apply).

**Comment by le-cds** [comment]
> The top `nodeComment` in my drawing is thus _not_ added at the moment?

Correct.

> Shall we clearly define it in the options doc: `comment*` spacings are only applied between the comment and the corresponding node. The spacing between comments and anything adjacent is computed as if the comment is a regular node (i.e. `nodeNode`, `nodeEdge`, etc. may apply).

Yep, I'll do that.

**Pull request merged**
