### PR TITLE
Fix always existing bug in model order port sorting.

### PR DESCRIPTION
**Pull request by soerendomroes**
Make sure that the order of incoming ports matches the order given by the previous layer.

Updated WEST side handling to fix the main issue. Moreover, there was a p1/p2 typo as well. 

This also makes port model order non-constraining for input ports same as the edge model order.
If one wants to constrain the port order one should use portConstraints.

- [x] I want to check whether I can also fix feedback edges with model order
- [x] Check the used examples into elk-models to document how it should behave.

### CODE REVIEW

**Comment by soerendomroes** [comment]
[This](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=HYewJgpgBAkgznArhAHAdgIwBUJwC5QDeAUMVOVBADYDWAdGAJYBOEAxnoyMAFxQBKMAOIAJLGQpsAnmyoQAQqwCGNRsADmdfMyV4I6qXwCyAeQAiAUQAyAfRP9L-CeTbc4jSMyPhqJ5p608HT0DPgAFfgsAMQt+GwszIQsAZWcoNmYQBDV1IzVGAFtGAC9dLmBA4P1DKAA5E1qLNIys9w084EKSsu46dVYIMClkgHdGPDYACzo8KQAHCD4TKKjSCihQSA2MIjT1qiUAI2ooACIMU7SAXzTB9WhgHYBaAD4NgCZd9f2jk-PTr7fIF3CBWX5UOB0NRUNSLKBBZB7Cg3dYoigg7ZQV4bAAsgKBB2OVDO7wBJCBwLA9zBRMh0NhfARECR5DRrLWFE2D0+5IphL+pOutyp3Kxb2AOI55C5GwAzPjvvziadZZdUcL7nKxR8NQ95diJVKNj5cQqfkSzji1cjSDdiDL5EowPIIJMlAA3LjMGAAdSUwDwWBAUUYAA9drdaAwWOxONw+IJROJ1tJZAplKoNJVdNVjOZrHYHLFmm4PBAvD4qH4Atoc6EoBForF4okUs1Mtl2vkiqU4xVayEavVGu3WjkOl1e+U+gMhqNxlMZvM4ctVusZY8zRQlWcLkL1hjNwb3mkNzyWVAd6dBeqDyKPtrHsQ7TKcPgXW7PSBmBGD1GmKwHDlAmwhiM0MhyIoEAqDk2aDnmli2PYjglsA7ieN4kBVv45ZwbmDaRDEcQJEkqQph2bS5N23R9nh9bDk05Fjl2nQ9j0FT9BAgzDGMEzTLMCxLCsp4mpuvIEuCu7Wuyd6ake4qyrqmIGop66ieeFKXpJ17SVAbKUPewCfCpRobopVxAA) shows the model I wanted to fix and the one I broke.

Apprently my bug only works for models were the edges originate from the same node.

**Comment by soerendomroes** [comment]
This does not seem to be everything. Somehow, [this](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUDiANYB0BM+AxnDBAHboBKAkgOIASAKkUVpZaIHACF8wMjCZgKAZzhRgcHGCzoAsgHkAIgFEAMgH1trA60HN5MAnk0Q7IbVDtQFSlWo1oACq30AMX1WY31dTn0AZUEoCHkbWU0ZGCQYAC8VRiYPZVV1dAA5bUL9WPjEsGSmVIys5gowfEIsKIB3eFoECjgsAAccdG1AwKI+6DgHJxc3dAAzUHkcASZHHDQmACY0AG8iNAxsCABXODQAbRt0wbRNgAYAGlu7gF0iAF8SAjB1rbQAWgAfBsAMwrNag3b7Q5YE5nS4ZG73J73N6fQg-SFAjYAFi+mKYIIBwK24LsuKhB0wsNOFyuSMezzR+N+OOJG02QA) is different.

**Comment by soerendomroes** [comment]
https://github.com/eclipse/elk-models/pull/22 adds the correctness test as an example model.

Maybe check, whether I should add more concrete tests for all corner cases here.
The test models in tests/layered/preserveOrder check all other cases while the basic correctness tests that check that big models have no corner cases left.

**Review by Eddykasp — CHANGES_REQUESTED** [review]
fix unconnected ports placement

**Comment by soerendomroes** [comment]
Fixes #1065

**Pull request merged**
