### PR TITLE
Issue #483: RectPacking: Initialize values with MIN_VALUE instead of -Infinity.

### PR DESCRIPTION
**Pull request by soerendomroes**
#483
Signed-off-by: Soeren Domroes <sdo@informatik.uni-kiel.de>

### CODE REVIEW

**Comment by uruuru** [comment]
Could you enlighten me why in this case min_value has to be used instead of -infty. The fact somewhat implies that the area internally worked in starts at (0,0), whereas in most other places of the algorithms we usually use (-infty, -infty).

**Comment by soerendomroes** [comment]
The width used in the algorithm might be added or subtracted. Doing so for -infinity results in NaN.

**Comment by uruuru** [comment]
You also changed the initial value for `maxScale`. Is this also expected to always be positive?

**Comment by soerendomroes** [comment]
You are right, the initial value of `maxScale` can be -infinity. This change will be included in my new pull request that reworks the whole algorithm.

**Pull request merged**
