### PR TITLE
Gitpod for Website

### PR DESCRIPTION
**Pull request by soerendomroes**
As requested in #857, feel free to correct the gitpod setup.

Signed-off-by: Soeren Domroes <sdo@informatik.uni-kiel.de>

### CODE REVIEW

**Review by spoenemann — COMMENTED** [review]
Thanks for adding this! I think the default workspace in Gitpod does not include Hugo. This would typically be added with a [custom Docker image](https://www.gitpod.io/docs/config-docker#configure-a-custom-dockerfile).

It would also be great to have the Maven build running in a separate terminal. I can take over parts of this config in case you don't have enough time.

**Comment by soerendomroes** [comment]
> Thanks for adding this! I think the default workspace in Gitpod does not include Hugo. This would typically be added with a [custom Docker image](https://www.gitpod.io/docs/config-docker#configure-a-custom-dockerfile).
> 
> It would also be great to have the Maven build running in a separate terminal. I can take over parts of this config in case you don't have enough time.

You are correct I don't really have time to configure gitpod, therefore, I would indeed be thankful if you could take over.

**Comment by soerendomroes** [comment]
@spoenemann Thank you, this looks very nice.

I noticed that the maven build takes quite long. Do we actually need the maven build?
The website preview opens on localhost:1313 and not on localhost:1313/elk. Is this something that is not possible in gitpod?

**Comment by spoenemann** [comment]
> I noticed that the maven build takes quite long. Do we actually need the maven build?

We need it to fetch dependencies, in case someone wants to browse the code in Gitpod.

> The website preview opens on localhost:1313 and not on localhost:1313/elk. Is this something that is not possible in gitpod?

I think there's no option to set a default path for an opened port. Can we forward from `/` to `/elk` in hugo serve?

**Pull request merged**
